experiment_name: kitti360-big
method_name: nelf-pro-large

trainer:
    visualize_seperate_eval_images: True
    visualize_scene: True
    load_dir: ~

pipeline:
    datamanager:
        eval_image_indices: ~
        dataparser:
            raw_loader: 'kitti360'
            orientation_method: 'none'
            downscale_factor: ~
            center_poses: True
            auto_scale_poses: False
            data: './data/KITTI360/data_2d_nvs_long_challenge/train_00'
            factor_pos_noise_scale: 0.0
    model:
        background_color: 'last_sample' 
        distortion_loss_mult: 0.0001
        distortion_loss_mult_factor_max: 20
        near_plane: 1.0
        far_plane: 1000
        init_sampler: 'sqrt' 
        near_basis: 16
        near_core: 2
        freq_theta: 5
        freq_phi: 2

        
vis: wandb